AllCops:
  TargetRubyVersion: 2.0

# module/class docs are in the c extension
Style/Documentation:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# long modules / classes are OK here
Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

# increase default complexity metrics
Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8
  Exclude: [ "test/*.rb" ]

Metrics/AbcSize:
  Max: 24
  Exclude: [ "test/*.rb" ]

Style/GlobalVars:
  Exclude: [ "ext/**/extconf.rb" ]

Style/NumericLiterals:
  Exclude: [ "test/*.rb" ]

Style/YodaCondition:
  Exclude: [ "test/*.rb" ]

Style/ClassAndModuleChildren:
  Exclude: [ "test/*.rb" ]

Metrics/MethodLength:
  Exclude: [ "test/*.rb" ]
