sudo: required
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
env:
  - CALC_VERSION=2.12.5.0   # version in deb 8 (12-Oct-2014)
  - CALC_VERSION=2.12.5.6   # latest unstable  (22-May-2017)
  - CALC_VERSION=2.12.6.0   # latest stable    (05-Jun-2017)
before_install:
  - gem install bundler     # travis ruby 2.0.0 installs bundler 1.7, update it
  - bin/install_calc.sh
after_success:
  - bin/todo.rb
