sudo: required
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5.0
  - 2.6.0
  - 2.7.0
env:
  - CALC_VERSION=2.12.7.1
  - CALC_VERSION=2.12.7.2
before_install:
  - gem install bundler
  - bin/install_calc.sh
after_success:
  - bin/todo.rb
