sudo: required
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
before_install:
  - gem install bundler     # travis ruby 2.0.0 installs bundler 1.7, update it
  - bin/install_calc.sh
after_success:
  - bin/todo.rb
